<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>XamarinPosed</RootNamespace>
    <AssemblyName>XamarinPosed</AssemblyName>
    <AndroidApplication>True</AndroidApplication>
    <AndroidManifest>Properties/AndroidManifest.xml</AndroidManifest>
    <AndroidSupportedAbis>armeabi-v7a;x86;arm64-v8a</AndroidSupportedAbis>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.AppCompat" />
    <PackageReference Include="Xamarin.AndroidX.Core" />
    <PackageReference Include="Xamarin.AndroidX.Material" />
    <PackageReference Include="Xamarin.AndroidX.CoordinatorLayout" />
    <PackageReference Include="Xamarin.AndroidX.ConstraintLayout" />
    <PackageReference Include="Xamarin.AndroidX.RecyclerView" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XPosedAPI\XPosedAPI.csproj" />
  </ItemGroup>

</Project>
